# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-08 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DRAapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantes',
            name='creador',
        ),
        migrations.AddField(
            model_name='ruta',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DRAapp.Usuario'),
        ),
    ]
