# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-26 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRAapp', '0002_auto_20181026_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fNac',
            field=models.DateField(null=True),
        ),
    ]
