# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DRAapp', '0002_auto_20181008_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='creador',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='DRAapp.Usuario'),
        ),
    ]
